---
Content:
  Keys: 
    - 1/VarDecParser
    - 1/LineCopier
DbPrefix: Base
SnipTree:
  Root: 0/Base
  0/Base:
    - [1/VarDecParser/constructor, 2, true]
    - [1/LineCopier/constructor, 2, true]
1/VarDecParser:
  constructor: |
    desc := "VarDecParser-" + time.Now().Format("150405.000000")
    dd.Desc = desc
    blacklist, err := elm.NewBlacklist(spec.SubNode("Arrangement"))
    if err != nil {
      return nil, err
    }
    return &VarDecParser{
      LineCopier: NewLineCopier(dd, count, desc),
      blacklist: blacklist,
      buffer: []interface{}{},
    }, nil
1/LineCopier:
  constructor: |
    desc := "LineCopier-" + time.Now().Format("150405.000000")
    if darg != nil {
      desc = darg[0]
    }
    return LineCopier{
      Desc: desc,
      dd: dd,
      skipLineCount: count,
    }