---
RemoteAddr: 127.0.0.1:6699
Step: scanify/84c8a33e-f6e5-11ed-984e-e7ae2cb0d52f/step1
Tasks:
  - EditCopy1
  # - CopyFile1
  - CopyFile2
EditCopy1: 
  Action: CopyFile
  AsyncTask: false
  Device: Genwork
  EnvironmentVars: []
  InputFile: trovedb:system/uri|github.repo/internal,incron.profile/template/cibuild/dev01/.profile
  OutputFile: trovedb:system/uri|github.repo/cibuild,incron.profile/cibuild/dev01/.profile
  PluginKey: cibuild/profile/edit
  Subject: CreateContainerRun
CopyFile1:
  Action: CopyFileWithTmsp
  AsyncTask: true
  Device: FileSystem
  InputFile: trovedb:system/uri|github.repo/internal,dropzone/cibuild.lib/dev01/manifest.yaml
  OutputFile: trovedb:system/uri|incron/dropzone,cibuild.lib/dev01/manifest.yaml
  Subject: CreateContainerRun
CopyFile2:
  Action: CopyFileWithTmsp
  AsyncTask: true
  Device: FileSystem
  InputFile: trovedb:system/uri|github.repo/internal,dropzone/cibuild/dev01/manifest.yaml
  OutputFile: trovedb:system/uri|incron/dropzone,cibuild/dev01/manifest.yaml
  Subject: CreateContainerRun