---
Sections:
  - createContainer
  - processPullCommandFlagsInRun
  - generateRootfsOpts
  - withContainerLabels
  - readKVStringsMapfFromLabel
  - parseKVStringsMapFromLogOpt
createContainer:
  - [ReplaceTextB, 'func createContainer', 'cmd *cobra.Command', 'cspec *CntrSpec']
  - [ReplaceTextA, setPlatformOptions, cmd, cspec]
  - [ReplaceTextA, generateRootfsOpts, cmd, cspec]
  - [ReplaceTextA, generateMountOpts, cmd, cspec]
  - [ReplaceTextA, parseKVStringsMapFromLogOpt, cmd, cspec]
  - [ReplaceTextA, withNerdctlOCIHook, 'withNerdctlOCIHook(cmd, id)', 'WithCntrizeOCIHook(id, dataStore, cspec)']
  - [ReplaceTextA, generateRuntimeCOpts, cmd, cspec]
  - [ReplaceTextA, withContainerLabels, cmd, cspec]
processPullCommandFlagsInRun:
  - [ReplaceTextB, 'func processPullCommandFlagsInRun', 'cmd *cobra.Command', 'cspec *CntrSpec']
  - [ReplaceTextA, processImageVerifyOptions, cmd, cspec]
  - [ReplaceTextA, cmd.OutOrStdout, cmd.OutOrStdout(), os.Stdout]
  - [ReplaceTextA, cmd.ErrOrStderr, cmd.ErrOrStderr(), os.Stderr]
generateRootfsOpts:
  - [ReplaceTextB, 'func generateRootfsOpts', 'cmd *cobra.Command', 'cspec *CntrSpec']
  - [ReplaceTextA, processPullCommandFlagsInRun, cmd, cspec]
withContainerLabels:
  - [ReplaceTextB, 'func withContainerLabels', 'cmd *cobra.Command', 'cspec *CntrSpec']
  - [ReplaceTextA, readKVStringsMapfFromLabel, cmd, cspec]
readKVStringsMapfFromLabel:
  - [ReplaceTextB, 'func readKVStringsMapfFromLabel', 'cmd *cobra.Command', 'cspec *CntrSpec']
parseKVStringsMapFromLogOpt:
  - [ReplaceTextB, 'func parseKVStringsMapFromLogOpt', 'cmd *cobra.Command', 'cspec *CntrSpec']
