---
Sections: 
  - import
  - createContainer
  - processPullCommandFlagsInRun
  - generateRootfsOpts
  - withContainerLabels
  - readKVStringsMapfFromLabel
  - parseKVStringsMapFromLogOpt
  - withStop
0/Workers: [LineCopier]
0/Starting: ['^import \(', false]
0/Ending: ['^\)$', 1, false]
1/Workers: [LineParserA, LineParserB]
1/Starting: ['^func createContainer', true]
1/Ending: ['^\}$', 1, true]
2/Workers: [LineParserA, LineParserB]
2/Starting: ['^func processPullCommandFlagsInRun', true]
2/Ending: ['^\}$', 1, true]
3/Workers: [LineParserA, LineParserB]
3/Starting: ['^func generateRootfsOpts', true]
3/Ending: ['^\}$', 3, true]
4/Workers: [LineParserB]
4/Starting: ['^func withContainerLabels', true]
4/Ending: ['^\}$', 1, true]
5/Workers: [LineParserA, LineParserB]
5/Starting: ['^func readKVStringsMapfFromLabel', true]
5/Ending: ['^\}$', 1, true]
6/Workers: [LineParserA, LineParserB]
6/Starting: ['^func parseKVStringsMapFromLogOpt', true]
6/Ending: ['^\}$', 1, true]
7/Workers: [LineCopier]
7/Starting: ['^func withStop', true]
7/Ending: [EOF, 1, true]