---
Content:
  - ''
  - '  if err |1| cspec.Err(); err != nil {'
  - '    |2|'
  - '  }'
  - '  cspec.ErrReset()'
  - ''
InsertTags: ['|1|', '|2|']
ContentIndex:
  '|1|': 1
  '|2|': 2
createContainer:
  '|1|': :=
  '|2|': return nil, nil, err
processPullCommandFlagsInRun:
  '|1|': :=
  '|2|': return types.ImagePullOptions{}, err
generateRootfsOpts:
  '|1|': =
  '|2|': return nil, nil, nil, err
readKVStringsMapfFromLabel:
  '|1|': :=
  '|2|': return nil, err
parseKVStringsMapFromLogOpt:
  '|1|': :=
  '|2|': return nil, err
