---
Sections: [import, WithoutRunMount, setPlatformOptions, generateNamespaceOpts, setOOMScoreAdj, withOOMScoreAdj]
0/Workers: [LineCopier]
0/Starting: ['^import \(', false]
0/Ending: ['^\)$', 1, false]
1/Workers: [LineCopier]
1/Starting: ['^func WithoutRunMount', true]
1/Ending: ['^\}$', 1, true]
2/Workers: [VarDecParser, LineEditor]
2/Starting: ['^func setPlatformOptions', true]
2/Ending: ['^\}$', 1, true]
3/Workers: [VarDecParser, LineEditor]
3/Starting: ['^func generateNamespaceOpts', true]
3/Ending: ['^\}$', 1, true]
4/Workers: [VarDecParser, LineEditor]
4/Starting: ['^func setOOMScoreAdj', true]
4/Ending: ['^\}$', 1, true]
5/Workers: [LineCopier]
5/Starting: ['^func withOOMScoreAdj', true]
5/Ending: [EOF, 1, true]