name: Release
on:
  push:
    branches:
      - main
env:
  GO111MODULE: on
jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    timeout-minutes: 40
    steps:
    - run: git config --global url.https://$GH_TOKEN@github.com/.insteadOf https://github.com/
    - uses: actions/checkout@v3
    - name: set release tag
      id : release-tag
      uses: mikefarah/yq@master
      with:
        cmd: echo "RELTAG=$(yq '.tag' 'attrib/manifest.yaml')" >> $GITHUB_OUTPUT
    - name: create artifacts archive
      run: make artifacts
    - name: prepare release notes
      run: |
        cat <<-EOF | tee /tmp/release-note.txt
        ${{ steps.release-tag.outputs.RELTAG }}

        $(attrib/generate-release-note.sh ${{ github.repository }} ${{ github.run_id }})
        EOF
    - name: create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        asset_flags=()
        for f in release/*; do asset_flags+=("-a" "$f"); done
        hub release create "${asset_flags[@]}" -F /tmp/release-note.txt ${{ steps.release-tag.outputs.RELTAG }}