name: Release
on:
  push:
    branches:
      - main
env:
  GO111MODULE: on
jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    timeout-minutes: 40
    steps:
    - run: git config --global url.https://$GH_TOKEN@github.com/.insteadOf https://github.com/
    - uses: actions/checkout@v3
    - name: create artifacts archive
      run: make artifacts
    - name: "SHA256SUMS"
      run: |
        ( cd release; sha256sum content-* ) | tee /tmp/SHA256SUMS
        mv /tmp/SHA256SUMS release/SHA256SUMS
    - name: the sha256sum of the SHA256SUMS file
      run: (cd release; sha256sum SHA256SUMS)
    - name: prepare the release note
      id: release-note-setter
      run: |
        tag="${GITHUB_REF##*/}"
        shasha=$(sha256sum release/SHA256SUMS | awk '{print $1}')
        "RELEASE_NOTES=$(cat <<-EOF
        ${tag}

        $(hack/generate-release-note.sh ${{ github.repository }} ${{ github.run_id }} $shasha)
        EOF
        )" >> $GITHUB_OUTPUT
    - name: create release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{ steps.release-note-setter.outputs.RELEASE_NOTES }}
        draft: false
        prerelease: false